#!/bin/bash

export WEZTERM_CONFIG_FILE="$APPDIR/usr/home/user/.config/wezterm/wezterm.lua"
export PATH="$APPDIR/usr/bin:$PATH"
export APPIMAGE_EXTRACT_AND_RUN=1 # required by zsh.appimage
export APPDIR2=$APPDIR
exec "$APPDIR/usr/bin/wezterm" "$@"
