#!/bin/bash

case $(file --dereference --brief --mime-type "$1") in
  image/*)          ( img2sixel --loop-control=disable                                                                      -w $((${2}*6)) "$1"                 ) > $PTS && exit 1 || echo "no libsixel :(" ;;
  application/pdf)  ( convert "${1}[0]" jpg:/tmp/imagemagick.png                                               && img2sixel -w $((${2}*3)) /tmp/imagemagick.png ) > $PTS && exit 1 || echo "no imagemagick :(" ;;
  video/*)          ( mpv --ao=null --vo-image-outdir=/tmp --vo=image --start=1 --frames=1 --really-quiet "$1" && img2sixel -w $((${2}*6)) /tmp/00000001.jpg    ) > $PTS && exit 1 || echo "no mpv :(";;
  *)                ( bat --style=plain --color=always "$1" )                                                                                                                      || echo "no bat :(" ;;
esac
