return {
  -- this table overrides highlights in all themes
  EndOfBuffer            = { bg = "NONE" },
  FoldColumn             = { bg = "NONE" },
  MsgArea                = { bg = "NONE" },
  NeoTreeNormal          = { bg = "NONE" },
  NeoTreeNormalNC        = { bg = "NONE" },
  Normal                 = { fg = "NONE", bg = "NONE" },
  NormalNC               = { fg = "NONE", bg = "NONE" },
  NormalSB               = { fg = "NONE", bg = "NONE" },
  SignColumn             = { bg = "NONE" },
  SignColumnSB           = { bg = "NONE" },
  TerminalBorder         = { bg = "NONE" },
  TerminalNormal         = { fg = "NONE", bg = "NONE" },
  TelescopeNormal        = { bg = "NONE" },
  WhichKeyFloat          = { bg = "NONE" },
  TermCursor             = { fg = "#1a1b26", bg = "#c0caf5" },
  TermCursorNC           = { fg = "#c0caf5", bg = "#3c3c3c" },
  CursorLine             = { bg = "#0c0c0c" },
  Folded                 = { bg = '#0c0c0c' },
  NeoTreeCursorLine      = { bg = "#16161e" },
  NeoTreeGitAdded        = { fg = "#495466" },
  NeoTreeGitConflict     = { fg = "#495466" },
  NeoTreeGitDeleted      = { fg = "#495466" },
  NeoTreeGitIgnored      = { fg = "#495466" },
  NeoTreeGitModified     = { fg = "#495466" },
  NeoTreeGitUnstaged     = { fg = "#495466" },
  NeoTreeGitUntracked    = { fg = "#495466" },
  NeoTreeGitStaged       = { fg = "#495466" },
  NeoTreeRootName        = { fg = "#7aa2f7" },
  NeoTreeTabActive       = { fg = "#c0caf5" },
  TelescopeResultsNormal = { fg = "#9c9c9c" },
  NormalFloat            = { fg = "#888888", bg = "NONE" },
  FloatBorder            = { fg = "#444444", bg = "NONE" },
  CmpItemAbbr            = { fg = "#888888", bg = "NONE" },
  Pmenu                  = { fg = "#444444", bg = "NONE" },
  TelescopeBorder        = { fg = "#171922", bg = "NONE" },
  TelescopeTitle         = { fg = "#303340", bg = "NONE" },
  WhichKeyBorder         = { fg = "#171922", bg = "NONE" },
  Winbar                 = { fg = "#495466" },
  WinbarNC               = { fg = "#495466" },
}
