return {
  ["Comment"]                = { fg = "#565f89", italic = false },
  ["Keyword"]                = { fg = "#7dcfff", italic = false },
  ["@keyword"]               = { fg = "#9d7cd8", italic = false },
  ["@keyword.function"]      = { fg = "#6e51a2" },
  ["@field"]                 = { fg = "#7aa2f7" },
  ["@property"]              = { fg = "#7aa2f7" },
  ["@string"]                = { fg = "#73daca" },
  ["@boolean"]               = { fg = "#1cff1c" },
  ["@number"]                = { fg = "#1cff1c" },
  ["@punctuation"]           = { fg = "#e8e8e8" },
  ["@punctuation.bracket"]   = { fg = "#515171" },
  ["@punctuation.delimiter"] = { fg = "#e8e8e8" },
  ["@punctuation.special"]   = { fg = "#515171" },
  ["@parameter"]             = { fg = "#e4f0fb" },
  ["@variable"]              = { fg = "#e4f0fb" },
  ["@tag"]                   = { fg = "#515171" },
  ["@tag.attribute"]         = { fg = "#91b4d5" },
  ["@tag.delimiter"]         = { fg = "#515171" },
  ["@constructor"]           = { fg = "#6e51a2" },
  ["Constant"]               = { fg = "#1cff1c" },
  ["String"]                 = { fg = "#73daca" },
  GitSignsAdd                = { fg = "#1abc9c" },
  GitSignsChange             = { fg = "#3c3cff" },
  GitSignsDelete             = { fg = "#880000" },
  IndentBlanklineChar        = { fg = "#3b4261" },
  IndentBlanklineContextChar = { fg = "#7aa2f7" },
  IlluminatedWordText        = { bg = "#080811" },
  IlluminatedWordRead        = { bg = "#080811" },
  IlluminatedWordWrite       = { bg = "#080811" },
  LspReferenceRead           = { bg = "#080811" },
  LspReferenceText           = { bg = "#080811" },
  LspReferenceWrite          = { bg = "#080811" },
  NotifyBackground           = { bg = "#000000" },
  NotifyDEBUGBody            = { fg = "#c0caf5" },
  NotifyDEBUGBorder          = { fg = "#2c2f44" },
  NotifyERRORBody            = { fg = "#c0caf5" },
  NotifyERRORBorder          = { fg = "#542931" },
  NotifyINFOBody             = { fg = "#c0caf5" },
  NotifyINFOBorder           = { fg = "#164a5b" },
  NotifyTRACEBody            = { fg = "#c0caf5" },
  NotifyTRACEBorder          = { fg = "#41385b" },
  NotifyWARNBody             = { fg = "#c0caf5" },
  NotifyWARNBorder           = { fg = "#55473a" },
  TelescopeSelection         = { bg = "#080811" },
  TelescopeSelectionCaret    = { bg = "#080811" },
  WinSeparator               = { fg = "#565f89" },
  rainbowcol1                = { fg = "#89ddff" },
  rainbowcol2                = { fg = "#2ac3de" },
  rainbowcol3                = { fg = "#7dcfff" },
  rainbowcol4                = { fg = "#1abc9c" },
  rainbowcol5                = { fg = "#7aa2f7" },
  rainbowcol6                = { fg = "#bb9af7" },
  rainbowcol7                = { fg = "#9d7cd8" },
}
